#   ____                   _
#  |  _ \    ___   __  __ (_)
#  | |_) |  / _ \  \ \/ / | |
#  |  _ <  | (_) |  >  <  | |
#  |_| \_\  \___/  /_/\_\ |_|
#         C O N F I G
#

log-level: debug
port: 4000

########### PACKAGE MANAGER ###########
# handles plugin dependencies
package-manager: pnpm

plugins:
  - _roxi/custom.plugin.js:
      foo: 'bar'
  - svelte:
  - routify:
  - rollup:
  - nollup:
      port: 3200
  - spassr:
      port: 3300
  - spassr:
      port: 3400
      ssr: true
  - postcss:
  - mdsvex:
  - vite:
  - debugger:
